# Generated by Django 3.2 on 2021-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryunit',
            name='code',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryunit',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
