# Generated by Django 3.2 on 2021-05-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210430_2241'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryUnit',
            new_name='Unit',
        ),
    ]
