# Generated by Django 3.2 on 2021-05-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='model',
            new_name='model_no',
        ),
    ]
