# Generated by Django 3.2 on 2021-05-04 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_locator_name_segment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
