# Generated by Django 3.2 on 2021-06-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='segment',
            new_name='segment_id',
        ),
    ]
