# Generated by Django 3.2 on 2021-06-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210620_1609'),
        ('inventory', '0020_warehouse_warehouse_bin_warehouse_box_warehouse_rack_warehouse_room_warehouse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
