# Generated by Django 3.1.7 on 2021-04-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210425_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='narritions',
            field=models.TextField(default='One'),
        ),
    ]
