# Generated by Django 3.2 on 2021-06-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_cost_center_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost_center',
            old_name='company_id',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='company_id',
            new_name='company',
        ),
    ]
