# Generated by Django 3.2 on 2021-06-15 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210615_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_center',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company'),
        ),
    ]
