# Generated by Django 3.2 on 2021-06-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_status_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status_Type',
        ),
    ]
