# Generated by Django 3.2.5 on 2021-07-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_userinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='firstName',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='lastName',
            field=models.CharField(max_length=150),
        ),
    ]
