# Generated by Django 3.2.5 on 2021-07-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20210711_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='Company',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
