# Generated by Django 3.2.5 on 2021-07-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_userinformation_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformation',
            old_name='Company',
            new_name='company',
        ),
    ]
