# Generated by Django 3.2.5 on 2021-07-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_rename_company_userinformation_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='company',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='company',
            field=models.ManyToManyField(to='company.Company'),
        ),
    ]
